### ISSUE TITLE
When the extension opens it shows different user level for a sec

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/extension#32]
It shows the beginner icon until it updates to the actual level. It should be cached so the change does not happen every time the user opens the extension

**Comment by marcosmenendez** [comment]
The solution found is a quick fix. Now, it shows a blank space before showing the right icon, but it should show the right icon from the start in the same way it shows the number of pieces, etc.

This info should be cached as well

**Comment by marcosmenendez** [comment]
Just one remark. We should always try to minimize the amount of memory used by the extension. It is critical to minimise the impact on browsing experience. So we should make sure we don't store the image in the extension memory

**Comment by JuanMenendezBuitrago** [comment]
I see the issue is tagged as "in developement" but just in case, a possible
solution would be to get the seniority level once from a function called in
the background.js and store it instead of calling it from the popup.js.
Therefore the value would be available when the user decides to open the
popup and also we would save api calls since the seniority level is not
likely to change during a single browsing session.

2015-05-12 10:18 GMT+02:00 Marcos Menendez <notifications@github.com>:

**Comment by marcosmenendez** [comment]
The same problem happens as well with the number of data points. If we want to get the very last number, then we should leave the space blank and then put the number, instead of putting a 0 and then the number

**Comment by marcosmenendez** [comment]
I moved to "in development" from "ready to test" by mistake. Nobody is working on it now. You can take it if you have time. Just change the owner.
