### ISSUE TITLE
Hide "trade non sensitive queries" option

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/extension#41]
Since we are not working with chango anymore, we should delete that line of the extension. This issue is linked to these other 2 of the webapp:
https://github.com/thegooddata/webapp/issues/155
https://github.com/thegooddata/webapp/issues/158

**Comment by JuanMenendezBuitrago** [comment]
The extension part of this issue is done.
Webapp related issues thegooddata/webapp#155 and thegooddata/webapp/#158 are pending

**Comment by atrandafir** [comment]
Please be clear if we need to hide or remove. @JuanMenendezBuitrago had deleted it, I've put it back and just hidden it because as far as I understand from https://github.com/thegooddata/webapp/issues/158 we might bring the functionality back someday.

**Comment by JuanMenendezBuitrago** [comment]
I deleted it because I've came across of quite a few, legacy code that
never gets executed, "just in case" and commented-out pieces and all in all
it was getting a bit messy. It was easy to restore in case we needed it in
the future anyway.



2015-05-23 14:48 GMT+02:00 Alexandru Trandafir Catalin <
notifications@github.com>:
