### ISSUE TITLE
Is height scroll working fine in the popup?

### ISSUE THREAD

**Issue by atrandafir** [thegooddata/extension#43]
I'm testing with this url:
http://openx.com/product/ad-server/

It detects 10 threats and when I open the Popup and click the Plus icon to open threats panel, it will push the rest of the content down and the content is bigger than the popup but the scrollbar on the right is not working properly so you cannot scroll to the bottom.

Could any of you test this on his computer?

**Comment by marcosmenendez** [comment]
I don't see ant scrollbar at all
![screen shot 2015-05-23 at 4 58 27 pm](https://cloud.githubusercontent.com/assets/1178350/7784629/08bc4974-016d-11e5-8d13-9298e8000346.png)

**Comment by atrandafir** [comment]
Looks like Juan changed something that could be related to this a year ago:
https://github.com/thegooddata/extension/commit/e1ac1f0be3cd3be7c7d6a1d07ea52bcfde2c40f3

@JuanMenendezBuitrago any idea on why or how this should be?

**Comment by JuanMenendezBuitrago** [comment]
I'll fix it.

2015-05-23 17:14 GMT+02:00 Alexandru Trandafir Catalin <
notifications@github.com>:

**Comment by atrandafir** [comment]
FYI just published extension to Google. But this is a minor issue anyway,
we'll include it in next version.

2015-05-23 17:27 GMT+02:00 Juan <notifications@github.com>:

**Comment by JuanMenendezBuitrago** [comment]
I think that what Alex describes happens depending on how tall your browser window is. In my case, if I go to lavanguardia.com and expand the threats list  (there are quite a few), the popup reaches almost the bottom of the browser window and therefore it doesn't grow any longer. Since I removed the vertical scroll bars, the content is clipped and the overflow is not shown.

The issue that started all this described a behavior (#17) that I can't reproduce any more. I remember that when we expended the threats list, the scroll bar showed up and stayed there even after collapsing the list. Probably it was a bug in Chrome that got solved, the thing is that now if I collapse the list, the scroll bar disappears so maybe I should enable the vertical scroll bar  again?

**Comment by atrandafir** [comment]
Well if now works fine if you enable it, I would do it. As I said in my case it is not allowing any scroll.

Do some testing and see what's the best, indeed the users "will" need it.

**Comment by JuanMenendezBuitrago** [comment]
Nah ... it has nothing to do with browser's window height. I better enable the vertical scroll bar as you say.

**Comment by JuanMenendezBuitrago** [comment]
Done
